pipeline {
    agent any
    environment {
        CI = 'true'
        MATERIAL_BUILD_DIR = '/var/lib/jenkins/material-build'
        MATERIAL_REPO_CREDENTIALS = credentials('winning-tfs-gwj')
    }
    stages {
        stage('Pre Git') {
            steps{
                sh "./src/materialPublish/scripts/test.sh"
                echo "物料仓库信息：${params.MATERIAL_REPOSITORY_NAME},${params.MATERIAL_REPOSITORY_GIT_PATH}"
                echo "物料信息：${params.MATERIAL_NAME},${params.MATERIAL_PATH},${params.MATERIAL_CATEGORY}"
                echo "发布信息：${params.PUBLISH_PREID},${params.PUBLISH_BUMP},${params.MATERIAL_VERSION},${params.PUBLISH_BRANCH_NAME},${params.BUILD_PATH}"
                echo "其他信息：${params.PUBLISH_PARAMS},${params.CACHE}"
                sh 'git config --global user.email "1857048691@163.com"'
                sh 'git config --global user.name "g_wj"'
                script {
                    echo 'create material dir'
                    dir("${MATERIAL_BUILD_DIR}/${params.MATERIAL_REPOSITORY_NAME}") {
                        checkout([$class: 'GitSCM', branches: [[name: "*/${params.PUBLISH_BRANCH_NAME}"]], extensions: [[$class: 'CleanBeforeCheckout', deleteUntrackedNestedRepositories: true]], userRemoteConfigs: [[credentialsId: '6057d8bb-cfde-4e06-8d62-df86b2dae3a8', url: params.MATERIAL_REPOSITORY_GIT_PATH]]])
                    }
                }
            }
        }
        stage('Pre Env') {
            steps {
                sh 'yarn config set registry http://172.16.9.242:8081/repository/npm-group/'
                script {
                    dir("${MATERIAL_BUILD_DIR}/${params.MATERIAL_REPOSITORY_NAME}") {
                        if (!fileExists('node_modules')) {
                            sh 'yarn --force --production --pure-lockfile'
                        } else {
                            if (!params.CACHE) {
                                echo "CACHE --- ${params.CACHE}"
                                deleteDir('node_modules')
                                sh 'yarn --force --production --pure-lockfile'
                            }
                        }
                    }
                    echo '检查物料目录node_modules'
                    dir("${MATERIAL_BUILD_DIR}/${params.MATERIAL_REPOSITORY_NAME}/${params.MATERIAL_PATH}") {
                        if (!fileExists('node_modules')) {
                            echo '没有node_modules'
                            sh 'yarn --force --production --pure-lockfile'
                        } else {
                            if (!params.CACHE) {
                                echo "CACHE --- ${params.CACHE}"
                                sh(script: 'rm -rf node_modules')
                                sh 'yarn --force --production --pure-lockfile'
                            }
                        }
                    }
                }
            }
        }
        stage('publish') {
            steps {
                script {
                    dir("${MATERIAL_BUILD_DIR}/${params.MATERIAL_REPOSITORY_NAME}/${params.MATERIAL_PATH}") {
                        if(params.PUBLISH_PREID == 'beta'){
                            echo "winex publish --beta  ${params.PUBLISH_BUMP} --skipGitStatusCheck ${params.PUBLISH_PARAMS}"
                            sh "winex publish --beta  ${params.PUBLISH_BUMP} --skipGitStatusCheck ${params.PUBLISH_PARAMS}"
                        }
                        if(params.PUBLISH_ISRELEASE == 'release'){
                            echo 'winex publish --release ${params.PUBLISH_BUMP} --skipGitStatusCheck'
                            sh 'winex publish --release ${params.PUBLISH_BUMP} --skipGitStatusCheck'
                        }
                        sh 'winex doc build'
                        sh 'winex build --app-type materialDemo'
                    }
                }
            }
        }
        stage('deploy') {
            steps {
                scho 'deploy'
            }
        }
    }
}


